In [1]:
import pandas as pd
import numpy as np

In [3]:
final = pd.read_csv("../data/processed/cic_sampled.csv")

final['Label'].value_counts()

Label
UDP       5476
Benign    1986
Syn       1872
MSSQL       46
UDPLag      16
Name: count, dtype: int64

In [4]:
final.shape

(9396, 78)

In [5]:
final.columns = final.columns.str.strip()
final.columns = final.columns.str.replace(" ", "_")
final.columns = final.columns.str.replace("/", "_")
final.columns = final.columns.str.replace(".", "_")

In [6]:
final.dtypes.value_counts()

float64    45
int64      32
str         1
Name: count, dtype: int64

In [7]:
for col in final.columns:
    if col != "Label" and final[col].dtype == "object":
        final[col] = pd.to_numeric(final[col], errors="coerce")

In [8]:
final.replace([np.inf, -np.inf], np.nan, inplace=True)
final.fillna(0, inplace=True)

,Protocol,Flow_Duration,Total_Fwd_Packets,Total_Backward_Packets,Fwd_Packets_Length_Total,Bwd_Packets_Length_Total,Fwd_Packet_Length_Max,Fwd_Packet_Length_Min,Fwd_Packet_Length_Mean,Fwd_Packet_Length_Std,...,Fwd_Seg_Size_Min,Active_Mean,Active_Std,Active_Max,Active_Min,Idle_Mean,Idle_Std,Idle_Max,Idle_Min,Label
0,6,54971,1,2,0.0,0.0,0.0,0.0,0.0,0.000000,...,20,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,6,1640402,4,0,0.0,0.0,0.0,0.0,0.0,0.000000,...,20,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Syn
2,6,73944689,10,0,0.0,0.0,0.0,0.0,0.0,0.000000,...,20,1.333333,0.57735,2.0,1.0,18486172.0,9768528.0,32731148.0,11755029.0,Syn
3,6,55627,1,1,0.0,0.0,0.0,0.0,0.0,0.000000,...,20,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,6,54672,1,2,0.0,0.0,0.0,0.0,0.0,0.000000,...,20,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9391,6,1319459,4,0,24.0,0.0,6.0,6.0,6.0,0.000000,...,20,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Syn
9392,6,60143273,14,8,84.0,48.0,6.0,6.0,6.0,0.000000,...,20,62.000000,51.46261,142.0,1.0,10023817.0,4289963.0,17594604.0,6847746.0,Syn
9393,17,218528,6,0,2088.0,0.0,393.0,321.0,348.0,35.088460,...,-1062718972,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,UDP
9394,17,105974,4,0,1438.0,0.0,389.0,330.0,359.5,34.063667,...,8,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,UDP
9395,17,21011,2,2,76.0,154.0,38.0,38.0,38.0,0.000000,...,20,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
final["Label_encoded"] = le.fit_transform(final["Label"])

le.classes_

array(['Benign', 'MSSQL', 'Syn', 'UDP', 'UDPLag'], dtype=object)

In [11]:
final.to_csv("../data/processed/cic_final_clean.csv", index=False)

In [10]:
final.dtypes.value_counts()

float64    45
int64      33
str         1
Name: count, dtype: int64

In [12]:
final.head()

,Protocol,Flow_Duration,Total_Fwd_Packets,Total_Backward_Packets,Fwd_Packets_Length_Total,Bwd_Packets_Length_Total,Fwd_Packet_Length_Max,Fwd_Packet_Length_Min,Fwd_Packet_Length_Mean,Fwd_Packet_Length_Std,...,Active_Mean,Active_Std,Active_Max,Active_Min,Idle_Mean,Idle_Std,Idle_Max,Idle_Min,Label,Label_encoded
0,6,54971,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0
1,6,1640402,4,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Syn,2
2,6,73944689,10,0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.333333,0.57735,2.0,1.0,18486172.0,9768528.0,32731148.0,11755029.0,Syn,2
3,6,55627,1,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0
4,6,54672,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0

In [13]:
cols_to_drop = [
    "Unnamed:_0", 
    "Flow_ID", 
    "Source_IP", 
    "Destination_IP",
    "Timestamp",
    "SimillarHTTP"
]

final = final.drop(columns=[c for c in cols_to_drop if c in final.columns])
final.shape

(9396, 79)

In [14]:
final = final[final["Label"] != "WebDDoS"]
final["Label"].value_counts()

Label
UDP       5476
Benign    1986
Syn       1872
MSSQL       46
UDPLag      16
Name: count, dtype: int64

In [15]:
X = final.drop(["Label", "Label_encoded"], axis=1)
y = final["Label_encoded"]

In [16]:
X.shape, y.shape

((9396, 77), (9396,))

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [18]:
import os, joblib
os.makedirs("../models", exist_ok=True)
joblib.dump(scaler, "../models/standard_scaler.pkl")

['../models/standard_scaler.pkl']

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

In [20]:
y_train.shape, y_test.shape

((7516,), (1880,))

In [21]:
X_train.shape, X_test.shape

((7516, 77), (1880, 77))

In [22]:
X_train.shape

(7516, 77)

In [23]:
final = pd.read_csv("../data/processed/cic_final_clean.csv")

In [27]:
print(final.columns)

Index(['Protocol', 'Flow_Duration', 'Total_Fwd_Packets',
       'Total_Backward_Packets', 'Fwd_Packets_Length_Total',
       'Bwd_Packets_Length_Total', 'Fwd_Packet_Length_Max',
       'Fwd_Packet_Length_Min', 'Fwd_Packet_Length_Mean',
       'Fwd_Packet_Length_Std', 'Bwd_Packet_Length_Max',
       'Bwd_Packet_Length_Min', 'Bwd_Packet_Length_Mean',
       'Bwd_Packet_Length_Std', 'Flow_Bytes_s', 'Flow_Packets_s',
       'Flow_IAT_Mean', 'Flow_IAT_Std', 'Flow_IAT_Max', 'Flow_IAT_Min',
       'Fwd_IAT_Total', 'Fwd_IAT_Mean', 'Fwd_IAT_Std', 'Fwd_IAT_Max',
       'Fwd_IAT_Min', 'Bwd_IAT_Total', 'Bwd_IAT_Mean', 'Bwd_IAT_Std',
       'Bwd_IAT_Max', 'Bwd_IAT_Min', 'Fwd_PSH_Flags', 'Bwd_PSH_Flags',
       'Fwd_URG_Flags', 'Bwd_URG_Flags', 'Fwd_Header_Length',
       'Bwd_Header_Length', 'Fwd_Packets_s', 'Bwd_Packets_s',
       'Packet_Length_Min', 'Packet_Length_Max', 'Packet_Length_Mean',
       'Packet_Length_Std', 'Packet_Length_Variance', 'FIN_Flag_Count',
       'SYN_Flag_Count', 'RST_Flag_Count', 'PSH_Flag_Count', 'ACK_Flag_Count',
       'URG_Flag_Count', 'CWE_Flag_Count', 'ECE_Flag_Count', 'Down_Up_Ratio',
       'Avg_Packet_Size', 'Avg_Fwd_Segment_Size', 'Avg_Bwd_Segment_Size',
       'Fwd_Avg_Bytes_Bulk', 'Fwd_Avg_Packets_Bulk', 'Fwd_Avg_Bulk_Rate',
       'Bwd_Avg_Bytes_Bulk', 'Bwd_Avg_Packets_Bulk', 'Bwd_Avg_Bulk_Rate',
       'Subflow_Fwd_Packets', 'Subflow_Fwd_Bytes', 'Subflow_Bwd_Packets',
       'Subflow_Bwd_Bytes', 'Init_Fwd_Win_Bytes', 'Init_Bwd_Win_Bytes',
       'Fwd_Act_Data_Packets', 'Fwd_Seg_Size_Min', 'Active_Mean', 'Active_Std',
       'Active_Max', 'Active_Min', 'Idle_Mean', 'Idle_Std', 'Idle_Max',
       'Idle_Min', 'Label', 'Label_encoded'],
      dtype='str')

In [29]:
final["packet_rate"] = (
    final["Total_Fwd_Packets"] + final["Total_Backward_Packets"]
) / (final["Flow_Duration"] + 1e-6)

In [30]:
list(final.columns)

['Protocol',
 'Flow_Duration',
 'Total_Fwd_Packets',
 'Total_Backward_Packets',
 'Fwd_Packets_Length_Total',
 'Bwd_Packets_Length_Total',
 'Fwd_Packet_Length_Max',
 'Fwd_Packet_Length_Min',
 'Fwd_Packet_Length_Mean',
 'Fwd_Packet_Length_Std',
 'Bwd_Packet_Length_Max',
 'Bwd_Packet_Length_Min',
 'Bwd_Packet_Length_Mean',
 'Bwd_Packet_Length_Std',
 'Flow_Bytes_s',
 'Flow_Packets_s',
 'Flow_IAT_Mean',
 'Flow_IAT_Std',
 'Flow_IAT_Max',
 'Flow_IAT_Min',
 'Fwd_IAT_Total',
 'Fwd_IAT_Mean',
 'Fwd_IAT_Std',
 'Fwd_IAT_Max',
 'Fwd_IAT_Min',
 'Bwd_IAT_Total',
 'Bwd_IAT_Mean',
 'Bwd_IAT_Std',
 'Bwd_IAT_Max',
 'Bwd_IAT_Min',
 'Fwd_PSH_Flags',
 'Bwd_PSH_Flags',
 'Fwd_URG_Flags',
 'Bwd_URG_Flags',
 'Fwd_Header_Length',
 'Bwd_Header_Length',
 'Fwd_Packets_s',
 'Bwd_Packets_s',
 'Packet_Length_Min',
 'Packet_Length_Max',
 'Packet_Length_Mean',
 'Packet_Length_Std',
 'Packet_Length_Variance',
 'FIN_Flag_Count',
 'SYN_Flag_Count',
 'RST_Flag_Count',
 'PSH_Flag_Count',
 'ACK_Flag_Count',
 'URG_Flag_Count',
 'CWE_Flag_Count',
 'ECE_Flag_Count',
 'Down_Up_Ratio',
 'Avg_Packet_Size',
 'Avg_Fwd_Segment_Size',
 'Avg_Bwd_Segment_Size',
 'Fwd_Avg_Bytes_Bulk',
 'Fwd_Avg_Packets_Bulk',
 'Fwd_Avg_Bulk_Rate',
 'Bwd_Avg_Bytes_Bulk',
 'Bwd_Avg_Packets_Bulk',
 'Bwd_Avg_Bulk_Rate',
 'Subflow_Fwd_Packets',
 'Subflow_Fwd_Bytes',
 'Subflow_Bwd_Packets',
 'Subflow_Bwd_Bytes',
 'Init_Fwd_Win_Bytes',
 'Init_Bwd_Win_Bytes',
 'Fwd_Act_Data_Packets',
 'Fwd_Seg_Size_Min',
 'Active_Mean',
 'Active_Std',
 'Active_Max',
 'Active_Min',
 'Idle_Mean',
 'Idle_Std',
 'Idle_Max',
 'Idle_Min',
 'Label',
 'Label_encoded',
 'packet_rate']

In [31]:
final.head()

,Protocol,Flow_Duration,Total_Fwd_Packets,Total_Backward_Packets,Fwd_Packets_Length_Total,Bwd_Packets_Length_Total,Fwd_Packet_Length_Max,Fwd_Packet_Length_Min,Fwd_Packet_Length_Mean,Fwd_Packet_Length_Std,...,Active_Std,Active_Max,Active_Min,Idle_Mean,Idle_Std,Idle_Max,Idle_Min,Label,Label_encoded,packet_rate
0,6,54971,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0,5.457423e-05
1,6,1640402,4,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Syn,2,2.438427e-06
2,6,73944689,10,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.57735,2.0,1.0,18486172.0,9768528.0,32731148.0,11755029.0,Syn,2,1.352362e-07
3,6,55627,1,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0,3.595376e-05
4,6,54672,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,Benign,0,5.487270e-05

In [32]:
list(final.columns)

['Protocol',
 'Flow_Duration',
 'Total_Fwd_Packets',
 'Total_Backward_Packets',
 'Fwd_Packets_Length_Total',
 'Bwd_Packets_Length_Total',
 'Fwd_Packet_Length_Max',
 'Fwd_Packet_Length_Min',
 'Fwd_Packet_Length_Mean',
 'Fwd_Packet_Length_Std',
 'Bwd_Packet_Length_Max',
 'Bwd_Packet_Length_Min',
 'Bwd_Packet_Length_Mean',
 'Bwd_Packet_Length_Std',
 'Flow_Bytes_s',
 'Flow_Packets_s',
 'Flow_IAT_Mean',
 'Flow_IAT_Std',
 'Flow_IAT_Max',
 'Flow_IAT_Min',
 'Fwd_IAT_Total',
 'Fwd_IAT_Mean',
 'Fwd_IAT_Std',
 'Fwd_IAT_Max',
 'Fwd_IAT_Min',
 'Bwd_IAT_Total',
 'Bwd_IAT_Mean',
 'Bwd_IAT_Std',
 'Bwd_IAT_Max',
 'Bwd_IAT_Min',
 'Fwd_PSH_Flags',
 'Bwd_PSH_Flags',
 'Fwd_URG_Flags',
 'Bwd_URG_Flags',
 'Fwd_Header_Length',
 'Bwd_Header_Length',
 'Fwd_Packets_s',
 'Bwd_Packets_s',
 'Packet_Length_Min',
 'Packet_Length_Max',
 'Packet_Length_Mean',
 'Packet_Length_Std',
 'Packet_Length_Variance',
 'FIN_Flag_Count',
 'SYN_Flag_Count',
 'RST_Flag_Count',
 'PSH_Flag_Count',
 'ACK_Flag_Count',
 'URG_Flag_Count',
 'CWE_Flag_Count',
 'ECE_Flag_Count',
 'Down_Up_Ratio',
 'Avg_Packet_Size',
 'Avg_Fwd_Segment_Size',
 'Avg_Bwd_Segment_Size',
 'Fwd_Avg_Bytes_Bulk',
 'Fwd_Avg_Packets_Bulk',
 'Fwd_Avg_Bulk_Rate',
 'Bwd_Avg_Bytes_Bulk',
 'Bwd_Avg_Packets_Bulk',
 'Bwd_Avg_Bulk_Rate',
 'Subflow_Fwd_Packets',
 'Subflow_Fwd_Bytes',
 'Subflow_Bwd_Packets',
 'Subflow_Bwd_Bytes',
 'Init_Fwd_Win_Bytes',
 'Init_Bwd_Win_Bytes',
 'Fwd_Act_Data_Packets',
 'Fwd_Seg_Size_Min',
 'Active_Mean',
 'Active_Std',
 'Active_Max',
 'Active_Min',
 'Idle_Mean',
 'Idle_Std',
 'Idle_Max',
 'Idle_Min',
 'Label',
 'Label_encoded',
 'packet_rate']

In [33]:
list(final.columns)

['Protocol',
 'Flow_Duration',
 'Total_Fwd_Packets',
 'Total_Backward_Packets',
 'Fwd_Packets_Length_Total',
 'Bwd_Packets_Length_Total',
 'Fwd_Packet_Length_Max',
 'Fwd_Packet_Length_Min',
 'Fwd_Packet_Length_Mean',
 'Fwd_Packet_Length_Std',
 'Bwd_Packet_Length_Max',
 'Bwd_Packet_Length_Min',
 'Bwd_Packet_Length_Mean',
 'Bwd_Packet_Length_Std',
 'Flow_Bytes_s',
 'Flow_Packets_s',
 'Flow_IAT_Mean',
 'Flow_IAT_Std',
 'Flow_IAT_Max',
 'Flow_IAT_Min',
 'Fwd_IAT_Total',
 'Fwd_IAT_Mean',
 'Fwd_IAT_Std',
 'Fwd_IAT_Max',
 'Fwd_IAT_Min',
 'Bwd_IAT_Total',
 'Bwd_IAT_Mean',
 'Bwd_IAT_Std',
 'Bwd_IAT_Max',
 'Bwd_IAT_Min',
 'Fwd_PSH_Flags',
 'Bwd_PSH_Flags',
 'Fwd_URG_Flags',
 'Bwd_URG_Flags',
 'Fwd_Header_Length',
 'Bwd_Header_Length',
 'Fwd_Packets_s',
 'Bwd_Packets_s',
 'Packet_Length_Min',
 'Packet_Length_Max',
 'Packet_Length_Mean',
 'Packet_Length_Std',
 'Packet_Length_Variance',
 'FIN_Flag_Count',
 'SYN_Flag_Count',
 'RST_Flag_Count',
 'PSH_Flag_Count',
 'ACK_Flag_Count',
 'URG_Flag_Count',
 'CWE_Flag_Count',
 'ECE_Flag_Count',
 'Down_Up_Ratio',
 'Avg_Packet_Size',
 'Avg_Fwd_Segment_Size',
 'Avg_Bwd_Segment_Size',
 'Fwd_Avg_Bytes_Bulk',
 'Fwd_Avg_Packets_Bulk',
 'Fwd_Avg_Bulk_Rate',
 'Bwd_Avg_Bytes_Bulk',
 'Bwd_Avg_Packets_Bulk',
 'Bwd_Avg_Bulk_Rate',
 'Subflow_Fwd_Packets',
 'Subflow_Fwd_Bytes',
 'Subflow_Bwd_Packets',
 'Subflow_Bwd_Bytes',
 'Init_Fwd_Win_Bytes',
 'Init_Bwd_Win_Bytes',
 'Fwd_Act_Data_Packets',
 'Fwd_Seg_Size_Min',
 'Active_Mean',
 'Active_Std',
 'Active_Max',
 'Active_Min',
 'Idle_Mean',
 'Idle_Std',
 'Idle_Max',
 'Idle_Min',
 'Label',
 'Label_encoded',
 'packet_rate']

In [34]:
final["packet_rate"] = (
    final["Total_Fwd_Packets"] + final["Total_Backward_Packets"]
) / (final["Flow_Duration"] + 1e-6)

In [35]:
final["packet_rate"] = (
    final["Total_Fwd_Packets"] + final["Total_Backward_Packets"]
) / (final["Flow_Duration"] + 1e-6)

In [36]:
cols_to_drop = [
    "Unnamed:_0", 
    "Flow_ID", 
    "Source_IP", 
    "Destination_IP",
    "Timestamp",
    "SimillarHTTP"
]

final = final.drop(columns=[c for c in cols_to_drop if c in final.columns])

In [39]:
import numpy as np

# 1. Packet Rate
final["packet_rate"] = (
    final["Total_Fwd_Packets"] + final["Total_Backward_Packets"]
) / (final["Flow_Duration"] + 1e-6)

# 2. Byte Rate
final["byte_rate"] = (
    final["Total_Fwd_Packets"] + final["Total_Backward_Packets"]
) / (final["Flow_Duration"] + 1e-6)

# 3. Burstiness
final["burstiness"] = final["Fwd_IAT_Std"] / (final["Fwd_IAT_Mean"] + 1e-6)

# 4. Flow Size
final["flow_size"] = (
    final["Total_Fwd_Packets"] + final["Total_Backward_Packets"]
)

# 5. Average Payload Size
final["avg_payload_size"] = (
    final["Total_Fwd_Packets"] + final["Total_Backward_Packets"]
) / (
    final["Total_Fwd_Packets"] + final["Total_Backward_Packets"] + 1e-6
)

# 6. Packet Size Variance
final["packet_size_var"] = final["Packet_Length_Variance"]

# 7. Fwd/Bwd Packet Ratio
final["fwd_bwd_ratio"] = (
    final["Total_Fwd_Packets"] / (final["Total_Backward_Packets"] + 1e-6)
)

# 8. Combined IAT Mean
final["iat_mean_combined"] = (
    final["Flow_IAT_Mean"] + final["Fwd_IAT_Mean"] + final["Bwd_IAT_Mean"]
) / 3

# 9. Total Flags
final["total_flags"] = (
    final["SYN_Flag_Count"] +
    final["ACK_Flag_Count"] +
    final["PSH_Flag_Count"] +
    final["URG_Flag_Count"] +
    final["RST_Flag_Count"]
)

# 10. Flag Intensity
final["flag_intensity"] = final["total_flags"] / (final["Flow_Duration"] + 1e-6)

# 11. SYN Dominance
final["syn_dominance"] = final["SYN_Flag_Count"] / (final["total_flags"] + 1e-6)

# 12. Packet Energy
final["packet_energy"] = final["Packet_Length_Mean"] * final["burstiness"]

In [40]:
final.to_csv("../data/processed/cic_final_behavior.csv", index=False)